## ========================= Project information =========================
report:
  Task_Num: DOExxx-bx       #任务单号
  Customer:                 #客户姓名
  Sales:                    #销售姓名
  Library: 墨卓单细胞 3’ 转录组 #如果是5’建库项目，请填写 "5’转录组测序".如果为核项目单细胞（核）3’ 转录组
  Executor: OEXXXX          #执行人员编号
  Species: 人-组织          #实验物种-组织类型  注意：物种与组织类型之间必须用中横线“-”连接，组织类型必填
  Sample_Num:               #样本数目
  Others: 3' scRNA          #如果是5’建库项目，请填写 "5' scRNA"。Please fill in "5' scRNA" if the project is 5′-end scRNA-seq.
  Reference:                #参考基因组路径，以下两行为人小鼠的最新版本路径
  #Reference: /data/database/mobivision-refdata/mobivision-GRCh38-2020-A/ # Lastest human ref
  #Reference: /data/database/mobivision-refdata/mobivision-mm10-2020-A/ # Lastest mouse ref

  # Project_Path:
  # Project_Start_Time:
  # Project_End_Time:
  # Data_Cleaning_Time:

## ========================= Email feedback =========================
email:
  emailto:
    - "xxx@oebiotech.com"    # 质控反馈邮件收件人，填写自己的邮箱。
  Project_management: "朱卉" # 项目部责任人
  Laboratory: "毕远芝经理" # 实验部门负责人

## ========================= Mobivision parameters =========================
mobivision_params:
  module:
    mobivision: true # change cellranger to mobivision
    upload_bam: False # 是否把bam上传到OBS，默认False (默认不生成bam文件)
    mobivision_report: False # 是否生成mobivision报告，默认不出，只质控不分析项目选择True
  version: "v2.1"  
  merge_samples: False # 是否merge samples,默认False
  intron: included  #默认included
  raw_data_obs_address: #可以列表形式填写多行，路径需要以'/'结尾。没有obs路径 填写 - "" 即可。
    - "obs://oe-scrna/Illumina-scRNA/HT2021-XXXX/"
  samples: all #用法1. 填写all 自动从raw_data_obs_address 获取所有样本名。
  #samples:    #用法2. 指定样本名。
  # - S1
  # - S2
  #samples:    #用法3. 指定样本名以及force-cells数量。注：方法2和方法3不可混用。
  # - S1: 5000
  Number_of_Reads: "350M"
## ========================= Report parameters =========================
report_params:
  module:
    cellranger_aggr: false
    create: false
    qc: false
    clustering: false
    marker: false
    celltyping: false
    diffexp: false
    report: false
    report_upload: false
  envmodules: "OESingleCell/3.0.d"
  samples_file: "config/samples.csv"
  libraries_file: "config/libraries.csv"
  diffexp_file: "config/diffexp.tsv"
  #ngene_numi_fold2sd: 2
  cut1: "median"  #可选median(中位数)，mean(平均值)
  cut2: "mad"     #可选median(中位数)、sd(标准差)或mad(绝对中位差)
  log10GenesPerUMI: 0.7  #最小值
  percent_mito: NULL # NULL: 自动判断
  percent_HB: 0.05
  rmdoublets: TRUE
  rmdoublets_methods: DoubletFinder
  roboust_linear_model: NULL #根据拟合线性模型处理离域值。例如nCount_RNA:nFeature_RNA;默认值：NULL
  reduct1: "pca"
  reduct2: "umap"
  resolution: 0.4
  pointsize: 0.5 # NULL：自动判断
  marker_test: "presto"
  diffexp_test: "presto"
  #celltypingdb: "hpca" # Human: hpca/blueprint_encode/schcl # Mouse: immgen/mouse.rnaseq/scmca

#========================================subtyping setting ==============================================================
subtype:
  module: 
    clustering: false
    find_marker: false
    celltypeing: false
    diff_gene: false
  robj: result/Count_QC/filtered.h5seurat
  sub_file: config/sub.tsv
  reduct1: pca
  reduct2: umap

#========================================cpu setting ==============================================================
cpu:
  # mobivision
  data_prepare: 1
  merge: 10
  mobivision: 10
  fastqc_check: 8
  bam_prepare: 1
  bam_upload: 1
  # report
  #cellranger_aggr: 8
  sctools_create: 6
  qc: 10
  clustering_bclust: 10
  clustering_summarize: 6
  clustering_coefficient: 6
  marker_findallmarkers: 10
  marker_heatmap: 10
  marker_visualize: 6
  celltyping: 6
  diffexp: 10
  diffexp_heatmap: 10
