$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  samples:
    type: string
  project:
    type: string
  reference:
    type: string
  raw_data_obs_address:
    type: string
  image_obs_address:
    type: string

# entries that have to be in the config file for successful validation
required:
  - samples_file
  #- project
  #- reference
